# Generated by Django 5.1.4 on 2024-12-30 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_rename_description_announcements_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcements',
            old_name='categories',
            new_name='category',
        ),
    ]
