# Generated by Django 5.1.4 on 2024-12-30 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_rename_categories_announcements_category'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='announcements',
            new_name='Announcement',
        ),
        migrations.RenameModel(
            old_name='comments',
            new_name='Comment',
        ),
    ]
