# Generated by Django 5.1.4 on 2024-12-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='post_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
