# Generated by Django 5.1.4 on 2024-12-25 12:11

import django.core.validators
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_lecturer_phone_number_lecturer_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='matric_no',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{2}+[a-zA-Z]{2}+[0-9]{6}$')]),
        ),
        migrations.AddField(
            model_name='student',
            name='reg_no',
            field=models.IntegerField(null=True),
        ),
    ]
