# Generated by Django 5.1.4 on 2024-12-25 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_lecturer_user_alter_student_matric_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matric_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{2}+[a-zA-Z]{2}+[0-9]{6}$', "Your Matric no isn't valid")]),
        ),
    ]
