# Generated by Django 5.1.4 on 2024-12-26 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_student_matric_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.IntegerField(choices=[(100, '100 Level'), (200, '200 Level'), (300, '300 Level'), (400, '400 Level'), (500, '500 Level')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='matric_no',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{2}+[a-zA-Z]{2}+[0-9]{6}$', "Your Matric no isn't valid")]),
        ),
    ]
