# Generated by Django 5.1.4 on 2024-12-27 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_organization_alter_department_abbreviation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matric_no',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{2}[a-zA-Z]{2}\\d{6}$', 'Invalid Matric No.')]),
        ),
    ]
