# Generated by Django 5.1.4 on 2024-12-30 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_staff_office'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
