# Generated by Django 5.1.4 on 2024-12-30 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_delete_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'Staff'},
        ),
    ]
